server:
  port: 8002
  tomcat:
    threads:
      max: 10
      min-spare: 1

spring:
  datasource:
    url: jdbc:mysql://mysql.sqlpub.com:3306/kiriraincat?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: ENC(2PdCcIt0wBJQoge4P7IWI5stb2TWPLJCG8F0I5nB0WjgLFtdXKBUfA8GlA/Xq7Ne)
    password: ENC(FRv3rig5U020Jow/b/DGlyl8lJkBgTipAzdeoo+3t0daeW8Z7oFjFnZB37Z5sF6mj8qC7z4sO0ai7pnxj/wuWQ==)
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false